const defaultTheme = require('tailwindcss/defaultTheme')

module.exports = {
  content: ['./src/**/*.{js,jsx}', './public/index.html'],
  theme: {
    extend: {
      colors: {
        primary: '#006565',
        'primary-container': '#008080',
        'primary-fixed': '#93f2f2',
        'primary-fixed-dim': '#76d6d5',
        'on-primary': '#ffffff',
        'on-primary-container': '#e3fffe',
        'on-primary-fixed': '#002020',
        'on-primary-fixed-variant': '#004f4f',
        'inverse-primary': '#76d6d5',

        secondary: '#795900',
        'secondary-container': '#ffbf00',
        'secondary-fixed': '#ffdfa0',
        'secondary-fixed-dim': '#fbbc00',
        'on-secondary': '#ffffff',
        'on-secondary-container': '#6d5000',
        'on-secondary-fixed': '#261a00',
        'on-secondary-fixed-variant': '#5c4300',

        tertiary: '#8b4823',
        'tertiary-container': '#a96039',
        'tertiary-fixed': '#ffdbcb',
        'tertiary-fixed-dim': '#ffb692',
        'on-tertiary': '#ffffff',
        'on-tertiary-container': '#fff9f7',
        'on-tertiary-fixed': '#341100',
        'on-tertiary-fixed-variant': '#733512',

        error: '#ba1a1a',
        'error-container': '#ffdad6',
        'on-error': '#ffffff',
        'on-error-container': '#93000a',

        surface: '#f8f7f4',
        'surface-dim': '#d7dbda',
        'surface-bright': '#f6faf9',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f0f4f3',
        'surface-container': '#ebefee',
        'surface-container-high': '#e5e9e8',
        'surface-container-highest': '#dfe3e2',
        'surface-variant': '#dfe3e2',
        'on-surface': '#181c1c',
        'on-surface-variant': '#3e4949',
        'inverse-surface': '#2c3131',
        'inverse-on-surface': '#edf2f1',

        outline: '#6e7979',
        'outline-variant': '#bdc9c8',
        'surface-tint': '#006a6a',
        background: '#f8f7f4',
        'on-background': '#181c1c',
        'stone-border': '#D3D1C7',
        'brand-dark': '#2C2C2A',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        '2xl': '12px',
        full: '9999px',
      },
      fontFamily: {
        'display-lg': ['"Plus Jakarta Sans"', ...defaultTheme.fontFamily.sans],
        'display-lg-mobile': ['"Plus Jakarta Sans"', ...defaultTheme.fontFamily.sans],
        'headline-md': ['"Plus Jakarta Sans"', ...defaultTheme.fontFamily.sans],
        'headline-sm': ['"Plus Jakarta Sans"', ...defaultTheme.fontFamily.sans],
        'body-lg': ['Inter', ...defaultTheme.fontFamily.sans],
        'body-md': ['Inter', ...defaultTheme.fontFamily.sans],
        'body-sm': ['Inter', ...defaultTheme.fontFamily.sans],
        'label-md': ['Inter', ...defaultTheme.fontFamily.sans],
        'input-text': ['Inter', ...defaultTheme.fontFamily.sans],
      },
      fontSize: {
        'display-lg': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'display-lg-mobile': ['32px', { lineHeight: '40px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'headline-sm': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'body-sm': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'label-md': ['14px', { lineHeight: '16px', letterSpacing: '0.01em', fontWeight: '600' }],
        'input-text': ['16px', { lineHeight: '24px', fontWeight: '400' }],
      },
      spacing: {
        xs: '4px',
        sm: '12px',
        md: '24px',
        lg: '48px',
        xl: '80px',
        gutter: '24px',
        'margin-mobile': '16px',
        base: '8px',
        'container-max': '1280px',
      },
      maxWidth: {
        'container-max': '1280px',
      },
    },
  },
  plugins: [require('@tailwindcss/forms')],
}
